nf_core_version: 3.1.2
repository_type: pipeline
template:
  author: "Luca Cozzut, Nicola Vison\xE0"
  description: The Spinning Jenny simulates the first industrial revolution using
    Agent Based Models
  force: false
  is_nfcore: true
  name: spinningjenny
  org: nf-core
  outdir: .
  version: 0.2dev
