bump_version: null
lint: null
nf_core_version: 3.0.2
org_path: null
repository_type: pipeline
template:
  author: "Luca Cozzut, Nicola Vison\xE0"
  description: The Spinning Jenny simulates the first industrial revolution using
    Agent Based Models
  force: false
  is_nfcore: true
  name: spinningjenny
  org: nf-core
  outdir: .
  skip_features: null
  version: 0.2dev
update: null
